# These valeus are filled in by maven which is why that's all specified in the pom
name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

api-version: 1.13
main: ${mainClass}